version: '2'

services:
  consul-1.9.1:
    image: consul:1.9.1
    container_name: consul-1.9.1
    command: consul  agent -server -data-dir=/consul/data  -node=agent-one -bind=0.0.0.0 -bootstrap-expect=1 -client=0.0.0.0 -ui
    ports:
      - 8500:8500
      - 8600:8600/udp
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ./data:/consul/data
      - ./config:/consul/config
    networks:
      - local-net

networks:
  local-net:
    external: true
